### PR TITLE
Add de.yaml

### PR DESCRIPTION
**Pull request by valentinbinotto**
Add an German version of the .yaml file. Would be great if you could take a look at it 🙏

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello and thank you for your contribution! Would you be interested in making your edits up in [our Weblate project](https://hosted.weblate.org/projects/privacy-badger/)? I know we don't have this properly documented yet, but we are working on it.

**Comment by valentinbinotto** [comment]
Sure, so i edit now the german version on Weblate. Should i make these changes in this request for this time here on github or should i just close the pull request and make it on weblate?

**Comment by ghostwords** [comment]
If you're happy with Weblate, excellent, let's close this PR. Weblate will automatically open (or update its existing) PR with your changes in their own commit(s) with proper attribution to your GitHub profile (assuming your Weblate and GitHub emails match).

**Comment by ghostwords** [comment]
OK, your Weblate commit is here but it looks like it didn't get attributed to your GitHub properly: a2d13b5fe056f7df2d765ab38f8b9f7ab768172d. Did you use a different email for Weblate?

**Comment by valentinbinotto** [comment]
Jap, you are right. I will change the mail address

**Comment by valentinbinotto** [comment]
It‘s now the correct address. I‘m sorry for this :)

**Comment by ghostwords** [comment]
OK, I made a few tweaks/fixes and pushed your translations live to privacybadger.org. Thank you again!

Looks like the first commit did not get its author info updated. Sorry about that. You could try adding that version of your email address to GitHub as an alternate email. I don't know if GitHub will let you add different versions of the same Gmail address, but maybe?

**Comment by ghostwords** [comment]
The latest (FAQ) translations are live on https://privacybadger.org/. (An FAQ entry gets added only when the entire entry is translated.)

**Pull request closed without merging**
