### PR TITLE
Fr translation

### PR DESCRIPTION
**Pull request by smiquee**

### CODE REVIEW

**Comment by ghostwords** [comment]
Hello and thank you for your contributions!

Would you be interested in making edits directly on [our Weblate project](https://hosted.weblate.org/projects/privacy-badger/)? I know we don't have this properly documented yet, but we are working on it. Let me know if you have any questions.

**Comment by smiquee** [comment]
Hello, and welcome ;)

Does this mean that I have to create an account on weblate to copy/paste each part within this tool?

It's a bit disappointing, but if it is how the "commit" has t be done, I will try to find some additional time to do it.

**Comment by ghostwords** [comment]
If you'd rather not make an account on Weblate, that's OK too. It's just that Weblate makes it easier to work on and review translations. Let me know if you'd rather not use Weblate, and then I will review your contributions here on GitHub. Once we get this PR merged, I'll update Weblate myself.

(By the way, if you make an account on Weblate using the same email as the email you use on GitHub, Weblate will generate commits that properly credit your GitHub account as the author.)

**Comment by smiquee** [comment]
I'm currently working on weblate ;)

Starting to complete the translation, trying to understand how it works, to submit modifications for already translated parts needing some fixes.

**Comment by smiquee** [comment]
I just finished the "translation upload" on weblate. Hope I've done it correctly.

The process was a bit fun, with nice edition help on some points. Interesting discovery of this tool.

**Comment by ghostwords** [comment]
I left a couple of comments and made some edits (mostly for consistency with extension translations) in Weblate.

Here are my changes on GitHub: https://github.com/EFForg/privacybadger-website/pull/106/commits/b68cce8a4a61d4564b34245d564066ef55dfc1db?diff=split&w=0

If I missed or messed anything up, feel free to edit or leave comments directly in Weblate.

Thank you again!

**Comment by ghostwords** [comment]
Your translations are now live on https://privacybadger.org/fr/.

**Pull request closed without merging**
