### PR TITLE
Fix firefox/firefox-on-android detection

### LINKED ISSUE #35: Browser detection seems off on new website
Getting "Privacy Badger for Firefox on Android is in BETA." but I'm on desktop Firefox ("Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0").

### PR DESCRIPTION
**Pull request by wioux**
[Firefox user agent string reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Android_version_40_and_below)

Closes #35.

### CODE REVIEW

**Comment by andresbase** [comment]
Thanks!
IMG_30CAAB4C14CB-1

**Comment by ghostwords** [comment]
Is this a screenshot from Firefox on Android?

**Comment by wioux** [comment]
Here is Firefox on Android vs. Desktop:

**Comment by ghostwords** [comment]
Looks good, I was just wondering what @andresbase's screenshot was.

**Pull request merged**
