### PR TITLE
Fix anchor links and links to /faq

### LINKED ISSUE #32: Update FAQ anchor links on new site to match old site to avoid breaking existing deep links
For example https://privacybadger-staging.d5.eff.org/#How-to-uninstall

and 

    new: https://privacybadger-staging.d5.eff.org/#what-is-pb
    current: https://www.eff.org/privacybadger/faq#What-is-Privacy-Badger

### PR DESCRIPTION
**Pull request by wioux**
Follow up to #54. Fixes #32. When matching old anchor links, we now look for both `#xyz` and `#faq-xyz` and treat them as the same. I also switched it so that only a prefix match on an old anchor is needed, which lets us avoid having to enter the entire escaped question exactly right.

I removed /faq as a simple alias for the site and instead have that redirecting to the faq in index.html.

I'm not sure why the faq has disappeared from some dev environments -- my only guess is that we're building with different versions of Hugo? In any case it would be good to upgrade to the latest release, so I've opened an issue for that (#56).

### CODE REVIEW

**Comment by wioux** [comment]
Oh yeaah, the lint failure.. I'm looking at that now.

**Comment by wioux** [comment]
hash-remap.js is a small enough file that I don't think linting is necessary, so I just added it to .eslintignore.

**Comment by ghostwords** [comment]
>my only guess is that we're building with different versions of Hugo?

Which version are you building with? I used `brew install hugo` on macOS, which got me `v0.68.3/extended`

**Comment by wioux** [comment]
I use v0.55.3/extended, which I took from the download URL in `.travis-yml`. This is what the Dockerfile builds with as well.

**Comment by ghostwords** [comment]
> I use v0.55.3/extended, which I took from the download URL in `.travis-yml`. This is what the Dockerfile builds with as well.

Yep, that was it, I see the FAQ contents now.

@daly We should fix the README as "install the extended version of Hugo" lead us to install the latest version.

**Comment by ghostwords** [comment]
@wioux Looks good, thank you!

One thing I noticed is that going to https://www.eff.org/privacybadger/faq does not send you to the FAQ section.

**Pull request merged**
